language: c

sudo: required

arch:
  script:
    - mkdir build && build
    - qmake ../wallpapers.pro
    - make

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
